<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>

<form id="import_form" method="post"
      action="<?php echo Mage::helper("adminhtml")->getUrl("importexport/export/export"); ?>">
    <input name="form_key" type="hidden" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>"/>

    <div>
        <label>
            Marca
            <select name="manufacturer">
                <option value>-</option>
                <?php
                $attribute = Mage::getSingleton('eav/config')
                    ->getAttribute(Mage_Catalog_Model_Product::ENTITY, 'manufacturer');

                if ($attribute->usesSource()) {
                    $options = $attribute->getSource()->getAllOptions(false);
                    foreach ($options as $option) : ?>
                        <option value="<?php echo $option['value']; ?>"><?php echo $option['label']; ?></option>
                    <?php endforeach;
                }
                ?>
            </select>
        </label>
    </div>

    <br>

    <div>
        <?php
        $attributes = Mage::getSingleton('eav/config')
            ->getEntityType(Mage_Catalog_Model_Product::ENTITY)
            ->getAttributeCollection()
            ->addSetInfo();

        /** @var Mage_Catalog_Model_Resource_Eav_Attribute $attribute */
        foreach ($attributes as $attribute) : ?>
            <div class="attribute">
                <label><?php echo $attribute->getFrontendLabel(); ?>
                    <input type="checkbox" name="att_<?php echo $attribute->getName(); ?>" value="1"</label> &nbsp;
            </div>
        <?php endforeach; ?>
    </div>

    <input type="submit" value="Esporta">
</form>

<style>
    .attribute {
        width: 100%;
        max-width: 40px;
        display: inline-block;
    }
</style>

<script>
    $j = jQuery.noConflict();
</script>