<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>

<form id="import_form" method="post" enctype="multipart/form-data">
    <input name="form_key" type="hidden" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>"/>

    <label>
        Import
        <input type="file" name="file">
    </label>

    <input type="submit" value="Importa">
</form>

<script>
    $j = jQuery.noConflict();

    $j(function () {

        var $form = $j("#import_form");
        $form.on("submit", function (e) {
            var formData = new FormData(this);
            $j.ajax({
                url: "<?php echo Mage::helper("adminhtml")->getUrl("importexport/import/ajaximport"); ?>",
                type: 'POST',
                data: formData,
                success: function (response) {
                    console.log(response);
                },
                cache: false,
                contentType: false,
                processData: false
            });
            e.preventDefault();
        });
    });

</script>
